version: '2.3'
services:
  api:
    image: openeats/openeats-api:1.5.1
    command: /startup/prod-entrypoint.sh
    restart: always
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      env_prod.list
  web:
    image: openeats/openeats-web:1.5.1
    command: yarn start
    restart: on-failure
#    depends_on:
#      - api
    volumes:
      - public-ui:/code/build
    env_file:
      env_prod.list
  db:
    image: mariadb:5.5.64
    restart: always
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 20
    env_file:
      env_prod.list
  nginx:
    image: openeats/openeats-nginx:1.5.1
    command: ./start.sh
    restart: always
    ports:
      - 8000:80
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
      - public-ui:/var/www/html/openeats-static/public-ui
    depends_on:
      - api
      - web
    env_file:
      env_prod.list
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openeats.rule=Host(\"h2881927.stratoserver.net\")"
      - "traefik.http.routers.openeats.entrypoints=web"
volumes:
  database:
  public-ui:
  static-files:
  site-media:
